version: '3'
services:
  k8s-eureka-naming-server:
    image: habeebcycle/k8s-eureka-naming-server:v1
    ports:
      - 8761:8761
    
  k8s-config-server:
    image: habeebcycle/k8s-config-server:v1
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://k8s-eureka-naming-server:8761/eureka
    depends_on:
      - k8s-eureka-naming-server
    ports:
      - 8888:8888
  
  k8s-service1:
    image: habeebcycle/k8s-service1:v1
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://k8s-eureka-naming-server:8761/eureka
    depends_on:
      - k8s-eureka-naming-server
      - k8s-config-server
    ports:
      - 9090:9090
  
  k8s-service2:
    image: habeebcycle/k8s-service2:v1
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://k8s-eureka-naming-server:8761/eureka
    restart: on-failure
    depends_on:
      - k8s-eureka-naming-server
      - k8s-config-server
    ports:
      - 9091:9091