apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-api-gateway
  name: k8s-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-api-gateway
    spec:
      containers:
      - image: habeebcycle/k8s-api-gateway:v1
        name: k8s-api-gateway
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-api-gateway
  name: k8s-api-gateway
spec:
  ports:
  - name: 9091-9091
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: k8s-api-gateway
  type: ClusterIP
status:
  loadBalancer: {}