apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-service1
  name: k8s-service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-service1
    spec:
      containers:
      - image: habeebcycle/k8s-service1:v1
        name: k8s-service1
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-service1
  name: k8s-service1
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: k8s-service1
  type: ClusterIP
status:
  loadBalancer: {}