spring:
  application:
    name: k8s-service1
  
  cloud:
    config:
      uri: ${CONFIG_SERVER:http://localhost:8888}

eureka:
  client:
      serviceUrl:
          defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
  port: 9090
