eureka:
    client:
        fetch-registry: false
        register-with-eureka: false

#Managing the logging
#logging:
#    level:
#        com:
#            netflix:
#                eureka: OFF
#                discovery: OFF

server:
    port: 8761

spring:
    application:
        name: k8s-eureka-naming-server

